function getRoofPrismPOB(para)
%getRoofPrismPOB - generate POB file for Roof Prism
%
%   Author: Terrence Xue
%   Last updated: 2021.6.2
%
%   This function generates POB file of Roof Prism for OpticStudio Zemax NSC Mode
%   Parameter para
%   Para.FileName,      POB File Name
%   Para.Thickness,     Prism Thickness£¬Unit: mm
%   Para.Height,        Prism Height£¬Unit: mm
%   Para.Width,         Prism Width£¬Unit: mm
%   Para.Wedge,         Prism Wedge, Unit: deg
%
%% -------------------------Example 01-----------------------------
% clc
% clear all
% global GB
% para.FileName = 'Roof_Prism';
% para.Thickness = 0.45;
% para.Height = 1.80;
% para.Width = 0.45;
% para.Wedge = 3.15;
% getRoofPrismPOB(para);

% -------------------------------------------------------------------------

    pobFileName = para.FileName;
    fid = fopen(fullfile(pwd, [pobFileName, '.pob']),'a+');
    fprintf(fid, '! Roof prism\n');
    fprintf(fid, ['! Generated by getRoofPrismPOB.m, ', date(),'\n']);
    fprintf(fid, '\n');
    fprintf(fid, '! front face vertices\n');
    fprintf(fid, ['V\t1\t',num2str(para.Width/2),'\t ',num2str(-para.Height/2), '\t0\n']);
    fprintf(fid, ['V\t2\t',num2str(-para.Width/2),'\t ',num2str(-para.Height/2), '\t0\n']);
    fprintf(fid, ['V\t3\t',num2str(para.Width/2),'\t ',num2str(para.Height/2), '\t0\n']);
    fprintf(fid, ['V\t4\t',num2str(-para.Width/2),'\t ',num2str(para.Height/2), '\t0\n\n']);

    fprintf(fid, ['V\t5\t',num2str(para.Width/2),'\t ',num2str(para.Height/2), '\t',num2str(para.Thickness),'\n']);
    fprintf(fid, ['V\t6\t',num2str(-para.Width/2),'\t ',num2str(para.Height/2),'\t',num2str(para.Thickness),'\n']);
    fprintf(fid, ['V\t7\t',num2str(para.Width/2),'\t0\t',num2str(para.Thickness+para.Height/2*tan(deg2rad(para.Wedge))),'\n']);
    fprintf(fid, ['V\t8\t',num2str(-para.Width/2),'\t0\t',num2str(para.Thickness+para.Height/2*tan(deg2rad(para.Wedge))),'\n']);
    fprintf(fid, ['V\t9\t',num2str(para.Width/2),'\t ',num2str(-para.Height/2), '\t',num2str(para.Thickness),'\n']);
    fprintf(fid, ['V\t10\t',num2str(-para.Width/2),'\t ',num2str(-para.Height/2),'\t',num2str(para.Thickness),'\n\n']);

    fprintf(fid, '! Front\n');
    fprintf(fid, 'R 1 2 4 3 0\n\n');

    fprintf(fid, '! Side \n');
    fprintf(fid, 'R 3 4 6 5 0\n\n');

    fprintf(fid, '! Top face\n');
    fprintf(fid, 'R 5 6 8 7 0\n\n');

    fprintf(fid, '!Bottom\n');
    fprintf(fid, 'R 1 2 10 9 0\n\n');

    fprintf(fid, '!Back\n');
    fprintf(fid, 'R 7 8 10 9 0\n\n');

    fprintf(fid, '!Sides\n');
    fprintf(fid, 'I 5 9\n');
    fprintf(fid, 'I 6 10\n');
    fprintf(fid, 'R 1 3 5 9 0\n');
    fprintf(fid, 'T 5 7 9 0\n');
    fprintf(fid, 'R 2 4 6 10 0\n');
    fprintf(fid, 'T 6 8 10 0\n');

    fclose(fid);
end

